language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# Linux
dist: xenial
sudo: required

# OS X only supports one image. Use the latest.
osx_image: xcode10.1

env:
  - TASK=check CONFIG_FLAGS="--enable-Werror --enable-test-Werror --enable-code-coverage"
  - TASK=distcheck
before_install:
  - sudo apt-get install -y gcc-multilib lcov libasan*
  - gem install coveralls-lcov
script:
  - autoreconf -iv
  - ./configure $CONFIG_FLAGS
  - touch libasn1parser/*.h
  - touch libasn1parser/*.l
  - touch libasn1parser/*.y
  - make $TASK
after_success:
  - test "x$CC" = "xgcc" -o "x$CC" = "xclang" && make code-coverage-capture && coveralls-lcov asn1c-*-coverage.info
after_failure:
  - find . -name test-suite.log -exec tail -v -n +1 {} +
